### ISSUE TITLE
[BUG] PlotlyJS fails to due ORCA

### ISSUE THREAD

**Issue by omrilesser** [JuliaPlots/Plots.jl#2912]
I'm trying to use Plots.jl with PlotlyJS to produce simple plots, e.g.
```
using Plots
plotlyjs()
x = range(0,stop=1,length=100)
y = x.^2
Plots.plot(x,y, legend=false, linecolor="red")
```
This throws the following error due to ORCA:
```
Info: Precompiling ORCA [47be7bcc-f1a6-5447-8b36-7eeeff7534fd]
ERROR: LoadError: ORCA not installed properly. Please call `Pkg.build("ORCA")`
```
So I tried the above build command and it also fails:
```
julia> Pkg.build("ORCA")
   Building ORCA → `C:\Users\omrile\.julia\packages\ORCA\jdK40\deps\build.log`
┌ Error: Error building `ORCA`:
│ internal/modules/cjs/loader.js:800
│     throw err;
│     ^
│ 
│ Error: Cannot find module './internal/streams/stream'
│ Require stack:
│ - C:\Users\omrile\.julia\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\node_modules\npm\node_modules\are-we-there-yet\node_modules\readable-stream\lib\_stream_readable.js
│ - C:\Users\omrile\.julia\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\node_modules\npm\node_modules\are-we-there-yet\node_modules\readable-stream\readable.js
│ - C:\Users\omrile\.julia\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\node_modules\npm\node_modules\are-we-there-yet\tracker-stream.js
│ - C:\Users\omrile\.julia\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\node_modules\npm\node_modules\are-we-there-yet\tracker-group.js
│ - C:\Users\omrile\.julia\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\node_modules\npm\node_modules\are-we-there-yet\index.js
│ - C:\Users\omrile\.julia\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\node_modules\npm\node_modules\npmlog\log.js
│ - C:\Users\omrile\.julia\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\node_modules\npm\bin\npm-cli.js
│     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
│     at Function.Module._load (internal/modules/cjs/loader.js:690:27)
│     at Module.require (internal/modules/cjs/loader.js:852:19)
│     at require (internal/modules/cjs/helpers.js:74:18)
│     at Object.<anonymous> (C:\Users\omrile\.julia\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\node_modules\npm\node_modules\are-we-there-yet\node_modules\readable-stream\lib\_stream_readable.js:50:14)
│     at Module._compile (internal/modules/cjs/loader.js:959:30)
│     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
│     at Module.load (internal/modules/cjs/loader.js:815:32)
│     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
│     at Module.require (internal/modules/cjs/loader.js:852:19) {
│   code: 'MODULE_NOT_FOUND',
│   requireStack: [
│     'C:\\Users\\omrile\\.julia\\artifacts\\345df2b824d1eacefab89d560a9e929ff24c0537\\node_modules\\npm\\node_modules\\are-we-there-yet\\node_modules\\readable-stream\\lib\\_stream_readable.js',
│     'C:\\Users\\omrile\\.julia\\artifacts\\345df2b824d1eacefab89d560a9e929ff24c0537\\node_modules\\npm\\node_modules\\are-we-there-yet\\node_modules\\readable-stream\\readable.js',
│     'C:\\Users\\omrile\\.julia\\artifacts\\345df2b824d1eacefab89d560a9e929ff24c0537\\node_modules\\npm\\node_modules\\are-we-there-yet\\tracker-stream.js',
│     'C:\\Users\\omrile\\.julia\\artifacts\\345df2b824d1eacefab89d560a9e929ff24c0537\\node_modules\\npm\\node_modules\\are-we-there-yet\\tracker-group.js',
│     'C:\\Users\\omrile\\.julia\\artifacts\\345df2b824d1eacefab89d560a9e929ff24c0537\\node_modules\\npm\\node_modules\\are-we-there-yet\\index.js',
│     'C:\\Users\\omrile\\.julia\\artifacts\\345df2b824d1eacefab89d560a9e929ff24c0537\\node_modules\\npm\\node_modules\\npmlog\\log.js',
│     'C:\\Users\\omrile\\.julia\\artifacts\\345df2b824d1eacefab89d560a9e929ff24c0537\\node_modules\\npm\\bin\\npm-cli.js'
│   ]
│ }
│ internal/modules/cjs/loader.js:800
│     throw err;
│     ^
│ 
│ Error: Cannot find module './internal/streams/stream'
│ Require stack:
│ - C:\Users\omrile\.julia\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\node_modules\npm\node_modules\are-we-there-yet\node_modules\readable-stream\lib\_stream_readable.js
│ - C:\Users\omrile\.julia\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\node_modules\npm\node_modules\are-we-there-yet\node_modules\readable-stream\readable.js
│ - C:\Users\omrile\.julia\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\node_modules\npm\node_modules\are-we-there-yet\tracker-stream.js
│ - C:\Users\omrile\.julia\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\node_modules\npm\node_modules\are-we-there-yet\tracker-group.js
│ - C:\Users\omrile\.julia\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\node_modules\npm\node_modules\are-we-there-yet\index.js
│ - C:\Users\omrile\.julia\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\node_modules\npm\node_modules\npmlog\log.js
│ - C:\Users\omrile\.julia\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\node_modules\npm\bin\npm-cli.js
│     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
│     at Function.Module._load (internal/modules/cjs/loader.js:690:27)
│     at Module.require (internal/modules/cjs/loader.js:852:19)
│     at require (internal/modules/cjs/helpers.js:74:18)
│     at Object.<anonymous> (C:\Users\omrile\.julia\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\node_modules\npm\node_modules\are-we-there-yet\node_modules\readable-stream\lib\_stream_readable.js:50:14)
│     at Module._compile (internal/modules/cjs/loader.js:959:30)
│     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
│     at Module.load (internal/modules/cjs/loader.js:815:32)
│     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
│     at Module.require (internal/modules/cjs/loader.js:852:19) {
│   code: 'MODULE_NOT_FOUND',
│   requireStack: [
│     'C:\\Users\\omrile\\.julia\\artifacts\\345df2b824d1eacefab89d560a9e929ff24c0537\\node_modules\\npm\\node_modules\\are-we-there-yet\\node_modules\\readable-stream\\lib\\_stream_readable.js',
│     'C:\\Users\\omrile\\.julia\\artifacts\\345df2b824d1eacefab89d560a9e929ff24c0537\\node_modules\\npm\\node_modules\\are-we-there-yet\\node_modules\\readable-stream\\readable.js',
│     'C:\\Users\\omrile\\.julia\\artifacts\\345df2b824d1eacefab89d560a9e929ff24c0537\\node_modules\\npm\\node_modules\\are-we-there-yet\\tracker-stream.js',
│     'C:\\Users\\omrile\\.julia\\artifacts\\345df2b824d1eacefab89d560a9e929ff24c0537\\node_modules\\npm\\node_modules\\are-we-there-yet\\tracker-group.js',
│     'C:\\Users\\omrile\\.julia\\artifacts\\345df2b824d1eacefab89d560a9e929ff24c0537\\node_modules\\npm\\node_modules\\are-we-there-yet\\index.js',
│     'C:\\Users\\omrile\\.julia\\artifacts\\345df2b824d1eacefab89d560a9e929ff24c0537\\node_modules\\npm\\node_modules\\npmlog\\log.js',
│     'C:\\Users\\omrile\\.julia\\artifacts\\345df2b824d1eacefab89d560a9e929ff24c0537\\node_modules\\npm\\bin\\npm-cli.js'
│   ]
│ }
│ ERROR: LoadError: failed process: Process(`'C:\Users\omrile\.julia\artifacts\345df2b824d1eacefab89d560a9e929ff24c0537\npm.cmd' config set scripts-prepend-node-path true`, ProcessExited(1)) [1]
│ 
│ Stacktrace:
│  [1] pipeline_error at .\process.jl:525 [inlined]
│  [2] run(::Cmd; wait::Bool) at .\process.jl:440
│  [3] run at .\process.jl:438 [inlined]
│  [4] main() at C:\Users\omrile\.julia\packages\ORCA\jdK40\deps\build.jl:4
│  [5] top-level scope at C:\Users\omrile\.julia\packages\ORCA\jdK40\deps\build.jl:30
│  [6] include(::String) at .\client.jl:457
│  [7] top-level scope at none:5
│ in expression starting at C:\Users\omrile\.julia\packages\ORCA\jdK40\deps\build.jl:30
└ @ Pkg.Operations D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Pkg\src\Operations.jl:942
```

I'm using Julia Pro 1.5.0-1 on Windows 10.

Thanks in advance!

**Comment by BeastyBlacksmith** [comment]
You should report that at the ORCA.jl repository

**Comment by omrilesser** [comment]
Reported:
[https://github.com/sglyon/ORCA.jl/issues/40#issue-680099411](https://github.com/sglyon/ORCA.jl/issues/40#issue-680099411)
